Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [25]:
import numpy as np

print('А не ввели бы вы длинну массива?')
array_lenght = int(round(float(input().replace(',','.'))))
print('Вы ввели примерно:', array_lenght)

my_array = np.arange(0, array_lenght)
my_array = my_array[::-1]
print('вот вам',my_array)

А не ввели бы вы длинну массива?
11
Вы ввели примерно: 11
вот вам [10  9  8  7  6  5  4  3  2  1  0]


Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [32]:
import numpy as np

print('А не ввели бы вы длинну массива?')
array_lenght = int(round(float(input().replace(',','.'))))
print('Вы ввели примерно', array_lenght, 'Вот ваша матрица:')

my_array = np.diag(np.arange(array_lenght), k=0)
print(my_array) 
my_summ = 0
for key in range(array_lenght):
    my_summ = my_summ + key

print('А вот и сумма диагонали:', my_summ)
    

А не ввели бы вы длинну массива?
50
Вы ввели примерно 50 Вот ваша матрица:
[[ 0  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  0  2 ...  0  0  0]
 ...
 [ 0  0  0 ... 47  0  0]
 [ 0  0  0 ...  0 48  0]
 [ 0  0  0 ...  0  0 49]]
А вот и сумма диагонали: 1225


Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [38]:
import numpy as np
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, -4] ] )
b = np.array( [4, 12, -3] )
print(np.linalg.solve(a, b))
print(np.allclose( np.dot(a, np.linalg.solve(a, b)), b ))

[-3.34285714  5.11428571  7.14285714]
True
